first_project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = "first_app"
urlpatterns = [
    path('',views.index,name="index"),
    path('form-name',views.form_name,name="form_name"),
    path('home',views.home,name="home"),
    path('about',views.about,name="about"),
    path('register',views.register,name="register")
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
urlpatterns = [
    path('',include('first_app.urls')),
    path('admin/', admin.site.urls),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    Name = models.CharField(max_length=50, unique=True)


class WebPage(models.Model):
    Name = models.CharField(max_length=50, unique=True)
    Topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    Url = models.URLField()


class AccessRecord(models.Model):
    WebPage = models.ForeignKey(WebPage, on_delete=models.CASCADE)
    Date = models.DateField()


class UserInfo(models.Model):
    User = models.OneToOneField(User,on_delete=models.CASCADE)
    DateOfBirth = models.DateField(blank=True)
    ProfilePicture = models.ImageField(upload_to='profile_pics',blank=True)

first_project/first_app/forms.py
from django import forms
from django.core import validators
import re
from django.contrib.auth.models import User
from first_app.models import UserInfo


def checkName(value):
    if(len(value)<=0):
        raise forms.ValidationError("Name should not be empty")
    regex = re.compile('[@_!#$%^&*()<>?/\|}{~:]')
    if(regex.search(value) != None):
         raise forms.ValidationError("Name should not contains any special character")


class BasicForm(forms.Form):
    name = forms.CharField(validators=[checkName])
    url = forms.URLField()


class UserForm(forms.ModelForm):

    password = forms.CharField(widget= forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email' , 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('ProfilePicture', 'DateOfBirth')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import WebPage
from . import forms

def index(request):
    webpages = WebPage.objects.order_by('id')
    data = {"Pages":webpages}
    return render(request, 'first_app/index.html', context=data)


def form_name(request):
    form = forms.BasicForm()
    if request.method == "POST":
        form = forms.BasicForm(request.POST)
        if(form.is_valid()):
            print("success")
    return render(request,'first_app/basicform.html',{'form':form})


def home(request):
    return render(request,'first_app/home.html')


def about(request):
    return render(request,'first_app/about.html')

def register(request):
    registered = False;
    userform = forms.UserForm()
    userInfoForm = forms.UserProfileInfoForm()
    if(request.method == "POST"):
        userForm = forms.UserForm(data=request.POST)
        userInfoForm = forms.UserProfileInfoForm(data=request.POST)
        if userForm.is_valid() and userInfoForm.is_valid():
            user = userForm.save()
            user.set_password(user.password)
            user.save()
            profile = userInfoForm.save(commit=False)
            profile.User = user;

            if 'ProfilePicture' in request.FILES:
                profile.ProfilePicture = request.FILES['ProfilePicture']

            profile.save()
            registered = True
        else:
            print(userForm.errors,userInfoForm.errors)
    else:
        userform = forms.UserForm()
        userInfoForm = forms.UserProfileInfoForm()
    return render(request,'first_app/register.html',{'user_form':userform,
                            'profile_form':userInfoForm,'registered':registered})
# Create your views here.

first_project/templates/first_app/about.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>This is about page</h1>
{% endblock %}

first_project/templates/first_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/app.css" %}">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
    <a href="{% url 'first_app:index' %}" class="navbar-brand">WebPage</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav">

            <a href="{% url 'first_app:home' %}" class="nav-item nav-link active">Home</a>
            <a href="{% url 'first_app:about' %}" class="nav-item nav-link">About</a>
            <a href="{% url 'first_app:form_name' %}" class="nav-item nav-link">Form</a>
            <a href="{% url 'first_app:register' %}" class="nav-item nav-link">Signup</a>
        </div>
    </div>
</nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}

    </div>
  </body>
</html>

first_project/templates/first_app/basicform.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<div>
  <form  method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" name="" value="Submit">
  </form>
</div>
{% endblock %}

first_project/templates/first_app/home.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>This is home page</h1>
{% endblock %}

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>Web pages</h1>
<div>
  {% if Pages %}
  <table>
    <thead>
      <th>Name</th>
      <th>URL</th>
    </thead>
    <tbody>
     {% for page in Pages %}
        <tr>
          <td>{{page.Name}}</td>
           <td>{{page.Url}}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
   <p>No records</p>
  {% endif %}
</div>
{% endblock %}

first_project/templates/first_app/register.html
{% extends "first_app/base.html" %}
{% block body_block %}

<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">
    {% if registered %}

      <h3>Thank you for registering!</h3>

    {% else %}

     <div class="row">
       <div class="col-md-12">
          <form class="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{user_form.as_p}}
            {{profile_form.as_p}}
            <input type="submit" name="" value="Register">
          </form>
       </div>
     </div>
     {% endif %}
  </div>
  <div class="col-md-2">

  </div>
</div>
{% endblock %}